services:
  douyin-downloader:
    environment:
      - TERM=xterm-256color
      - TZ=Asia/Shanghai
    tty: true
    stdin_open: true
    build:
      context: ./douyin-downloader
      dockerfile: Dockerfile
    container_name: douyin-downloader
    volumes:
      - ./data.db:/app/data.db
      - ./config.yml:/app/config.yml
      - ./logs:/app/logs
      - /nas_rpa_video_files/big_spider_data/douyin-downloader/抖音短视频:/app/Downloaded